@WebAPI_HostAddress = http://localhost:5034

GET {{WebAPI_HostAddress}}/Fruits/
###

POST {{WebAPI_HostAddress}}/Fruits/
Content-Type: application/json

"Cherry"
###


GET {{WebAPI_HostAddress}}/Fruits/58796835-7cad-40dd-93eb-395b1cc4ddfe
###


Put {{WebAPI_HostAddress}}/Fruits/58796835-7cad-40dd-93eb-395b1cc4ddfe
Content-Type: application/json

"Watermelon"
###


DELETE {{WebAPI_HostAddress}}/Fruits/f96937cc-e51e-42b6-8ba9-14742c2b69ce
###