@HostAddress = https://localhost:7298

### Get all fruits
GET {{HostAddress}}/api/Fruits

### Add new fruit
POST {{HostAddress}}/api/Fruits
Accept: application/json
Content-Type: application/json

"nanana"

###
@Id = 485e90dd-7f2f-4f47-acb8-a4bec43c8ae2

### Get specific fruit by Id
GET {{HostAddress}}/api/Fruits/{{Id}}

### Update existing fruit
PUT {{HostAddress}}/api/Fruits/{{Id}}
Accept: application/json
Content-Type: application/json

"nananaaaaaaa"

### Delete existing fruit
DELETE {{HostAddress}}/api/Fruits/{{Id}}